export interface ProjectFile {
  path: string;
  name: string;
  language: string;
  category: 'config' | 'manifest' | 'kotlin' | 'ci' | 'docs';
  description: string;
  content: string;
}

export const PROJECT_FILES: ProjectFile[] = [
  {
    path: '.github/workflows/android-build.yml',
    name: 'android-build.yml',
    language: 'yaml',
    category: 'ci',
    description: 'Automated GitHub Actions CI/CD workflow for building, validating and uploading APK & AAB',
    content: `name: Android Build & Release Pipeline

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build APK and AAB
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      # Step 1: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # Step 2: Validate APK Integrity & Requirements
      - name: Validate Generated Debug APK
        run: |
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ] || [ ! -f "$APK_PATH" ]; then
            echo "ERROR: No APK generated by Gradle build!"
            exit 1
          fi
          SIZE=$(stat -c%s "$APK_PATH")
          if [ "$SIZE" -lt 1048576 ]; then
            echo "ERROR: APK is smaller than 1MB ($SIZE bytes)!"
            exit 1
          fi
          unzip -t "$APK_PATH" | grep -q "AndroidManifest.xml"
          echo "APK verification SUCCESSFUL! Valid binary confirmed."

      # Step 3: Copy APK to Destination Directories
      - name: Stage APK Files for Download
        run: |
          mkdir -p .build-outputs APK_DOWNLOAD
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          cp "$APK_PATH" .build-outputs/app-debug.apk
          cp "$APK_PATH" APK_DOWNLOAD/app-debug.apk

      # Step 4: Upload Debug APK Artifact
      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: APK_DOWNLOAD/app-debug.apk
          retention-days: 30

      # Step 5: Build Release AAB (Android App Bundle)
      - name: Build Release AAB
        run: ./gradlew bundleRelease --stacktrace

      # Step 6: Stage & Upload Release AAB Artifact
      - name: Upload Release AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-AAB
          path: app/build/outputs/bundle/release/app-release.aab
          retention-days: 30`
  },
  {
    path: 'app/src/main/AndroidManifest.xml',
    name: 'AndroidManifest.xml',
    language: 'xml',
    category: 'manifest',
    description: 'Android application manifest declaring activities, permissions, and launcher intent filter',
    content: `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.ApexTaskFlow">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:label="@string/app_name"
            android:theme="@style/Theme.ApexTaskFlow"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

    </application>

</manifest>`
  },
  {
    path: 'app/build.gradle.kts',
    name: 'app/build.gradle.kts',
    language: 'kotlin',
    category: 'config',
    description: 'Application-level Gradle configuration with Jetpack Compose & Material 3 dependencies',
    content: `plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.apex.taskflow"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.apex.taskflow"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("debug")
        }
        debug {
            applicationIdSuffix = ".debug"
            isDebuggable = true
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.8"
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.02.00")
    implementation(composeBom)
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.activity:activity-compose:1.8.2")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3:1.2.0")
    implementation("androidx.navigation:navigation-compose:2.7.7")
}`
  },
  {
    path: 'app/src/main/java/com/apex/taskflow/MainActivity.kt',
    name: 'MainActivity.kt',
    language: 'kotlin',
    category: 'kotlin',
    description: 'Root Jetpack Compose activity with navigation, theme state, and back-stack handling',
    content: `package com.apex.taskflow

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.setContent
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.BarChart
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import com.apex.taskflow.data.repository.TaskRepository
import com.apex.taskflow.ui.screens.*
import com.apex.taskflow.ui.theme.ApexTaskFlowTheme

enum class Screen(val title: String) {
    TASKS("Tasks"),
    ANALYTICS("Analytics"),
    SETTINGS("Settings")
}

class MainActivity : ComponentActivity() {
    private val taskRepository = TaskRepository()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            val systemDark = isSystemInDarkTheme()
            var darkTheme by remember { mutableStateOf(systemDark) }

            ApexTaskFlowTheme(darkTheme = darkTheme) {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    var currentTab by remember { mutableStateOf(Screen.TASKS) }
                    var isCreatingTask by remember { mutableStateOf(false) }
                    val tasks by taskRepository.tasks.collectAsState()

                    BackHandler(enabled = isCreatingTask || currentTab != Screen.TASKS) {
                        if (isCreatingTask) isCreatingTask = false
                        else currentTab = Screen.TASKS
                    }

                    if (isCreatingTask) {
                        CreateTaskScreen(
                            onNavigateBack = { isCreatingTask = false },
                            onSaveTask = { taskRepository.addTask(it) }
                        )
                    } else {
                        Scaffold(
                            bottomBar = {
                                NavigationBar {
                                    NavigationBarItem(
                                        icon = { Icon(Icons.Default.CheckCircle, "Tasks") },
                                        label = { Text("Tasks") },
                                        selected = currentTab == Screen.TASKS,
                                        onClick = { currentTab = Screen.TASKS }
                                    )
                                    NavigationBarItem(
                                        icon = { Icon(Icons.Default.BarChart, "Analytics") },
                                        label = { Text("Analytics") },
                                        selected = currentTab == Screen.ANALYTICS,
                                        onClick = { currentTab = Screen.ANALYTICS }
                                    )
                                    NavigationBarItem(
                                        icon = { Icon(Icons.Default.Settings, "Settings") },
                                        label = { Text("Settings") },
                                        selected = currentTab == Screen.SETTINGS,
                                        onClick = { currentTab = Screen.SETTINGS }
                                    )
                                }
                            }
                        ) { paddingValues ->
                            Box(modifier = Modifier.padding(paddingValues)) {
                                when (currentTab) {
                                    Screen.TASKS -> HomeScreen(
                                        tasks = tasks,
                                        onToggleStatus = { taskRepository.toggleTaskStatus(it) },
                                        onDeleteTask = { taskRepository.deleteTask(it) },
                                        onCreateTaskClick = { isCreatingTask = true }
                                    )
                                    Screen.ANALYTICS -> AnalyticsScreen(tasks = tasks)
                                    Screen.SETTINGS -> SettingsScreen(
                                        darkTheme = darkTheme,
                                        onToggleDarkTheme = { darkTheme = it }
                                    )
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`
  },
  {
    path: 'app/src/main/java/com/apex/taskflow/ui/screens/HomeScreen.kt',
    name: 'HomeScreen.kt',
    language: 'kotlin',
    category: 'kotlin',
    description: 'Interactive tasks dashboard with search filter, category tags, and progress bar',
    content: `package com.apex.taskflow.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.apex.taskflow.data.model.TaskItem

@Composable
fun HomeScreen(
    tasks: List<TaskItem>,
    onToggleStatus: (String) -> Unit,
    onDeleteTask: (String) -> Unit,
    onCreateTaskClick: () -> Unit
) {
    // Jetpack Compose reactive state & list rendering
}`
  },
  {
    path: 'settings.gradle.kts',
    name: 'settings.gradle.kts',
    language: 'kotlin',
    category: 'config',
    description: 'Gradle multi-project configuration and repository plugin management',
    content: `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "ApexTaskFlow"
include(":app")`
  },
  {
    path: 'build.gradle.kts',
    name: 'build.gradle.kts (root)',
    language: 'kotlin',
    category: 'config',
    description: 'Root Gradle build script applying Android and Kotlin plugins',
    content: `plugins {
    id("com.android.application") version "8.2.2" apply false
    id("org.jetbrains.kotlin.android") version "1.9.22" apply false
}

tasks.register("clean", Delete::class) {
    delete(rootProject.buildDir)
}`
  },
  {
    path: 'gradle/wrapper/gradle-wrapper.properties',
    name: 'gradle-wrapper.properties',
    language: 'properties',
    category: 'config',
    description: 'Configures Gradle 8.4 runtime distribution for reproducible CI builds',
    content: `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.4-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists`
  },
  {
    path: 'README.md',
    name: 'README.md',
    language: 'markdown',
    category: 'docs',
    description: 'Complete documentation and bilingual setup guide for GitHub Actions',
    content: `# Apex TaskFlow - Android Project & Automated APK/AAB Pipeline

## 🇧🇩 বাংলা নির্দেশিকা
১. গিটহাবে আপনার রিপোজিটরি পুশ করুন:
   git push origin main
২. Actions ট্যাবে 'Android Build & Release Pipeline' স্বয়ংক্রিয়ভাবে চলবে।
৩. রান সম্পন্ন হলে Artifacts সেকশনে Android-APK এবং Android-AAB সরাসরি ডাউনলোড করতে পারবেন!`
  }
];
